spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device-manager
    username: postgres
    password: root

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true